groups:
  - name: NetworkSecurity
    rules:
      # Policy Violation Alerts
      - alert: HighPolicyViolations
        expr: rate(netsentinel_policy_violations_total[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High rate of policy violations detected
          description: "Pod {{ $labels.pod }} is violating network policies at a rate of {{ $value }} violations/minute"

      - alert: PersistentPolicyViolations
        expr: netsentinel_policy_violations_total > 100
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: Persistent policy violations detected
          description: "Pod {{ $labels.pod }} has accumulated {{ $value }} policy violations"

      # Anomaly Detection Alerts
      - alert: HighAnomalyScore
        expr: netsentinel_anomaly_score > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High anomaly score detected
          description: "Pod {{ $labels.pod }} has an anomaly score of {{ $value }} for {{ $labels.type }}"

      - alert: SuddenTrafficSpike
        expr: rate(netsentinel_traffic_bytes_total[1m]) / rate(netsentinel_traffic_bytes_total[5m]) > 3
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: Sudden traffic spike detected
          description: "Pod {{ $labels.pod }} traffic rate increased by {{ $value }}x"

      # Lateral Movement Alerts
      - alert: ExcessiveLateralConnections
        expr: netsentinel_lateral_connections > 50
        for: 10m
        labels:
          severity: critical
        annotations:
          summary: Excessive lateral movement detected
          description: "Pod {{ $labels.pod }} has established {{ $value }} lateral connections"

      - alert: HighLateralConnectionRate
        expr: rate(netsentinel_lateral_connection_rate[5m]) > 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High lateral movement rate detected
          description: "Pod {{ $labels.pod }} is establishing {{ $value }} lateral connections/minute"

      # Network Traffic Alerts
      - alert: HighConnectionRate
        expr: rate(netsentinel_traffic_connections_total[5m]) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High connection rate detected
          description: "Pod {{ $labels.pod }} is establishing {{ $value }} connections/minute"

      - alert: ExcessiveBandwidth
        expr: rate(netsentinel_traffic_bytes_total[5m]) > 1e8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Excessive bandwidth usage detected
          description: "Pod {{ $labels.pod }} is using {{ $value }} bytes/second"

      # Compliance Alerts
      - alert: PolicyComplianceDegradation
        expr: netsentinel_policy_compliance < 0.8
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: Policy compliance degradation detected
          description: "Pod {{ $labels.pod }} compliance with policy {{ $labels.policy }} has dropped to {{ $value }}"

      - alert: CriticalPolicyViolation
        expr: netsentinel_policy_compliance == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Critical policy violation detected
          description: "Pod {{ $labels.pod }} is completely non-compliant with policy {{ $labels.policy }}" 