global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts.yaml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Alertmanager service address
          - "alertmanager:9093"

scrape_configs:
  - job_name: 'netsentinel'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: '/metrics'
    scheme: 'http' 